import type { Metadata } from "next";
import Nav from "../components/Nav";
import Footer from "../components/Footer";
import PartnerForm from "./PartnerForm";

export const metadata: Metadata = {
  title: "Partner With SuppVis",
  description:
    "We are building the most trusted supplement platform on the internet. If you make a great product, conduct research, or serve health-focused audiences, we want to work together.",
};

export default function PartnershipsPage() {
  return (
    <>
      <Nav />
      <main className="pt-32 md:pt-40 pb-24 px-6">
        <div className="max-w-[760px] mx-auto">
          {/* Hero */}
          <h1 className="font-headline font-extrabold text-3xl sm:text-4xl md:text-5xl text-text-primary mb-6 leading-tight">
            Partner With SuppVis
          </h1>
          <div className="space-y-4 text-[15px] text-text-secondary leading-[1.75] mb-16">
            <p>
              SuppVis is building the personalized supplement platform we wished
              existed. Every recommendation traces back to peer-reviewed
              evidence. Every interaction is screened against the user&rsquo;s
              medications and conditions. Every brand we work with meets a clear
              quality bar.
            </p>
            <p>
              We are pre-launch and selective about who we work with. If your
              product, research, or platform fits what we&rsquo;re building, we
              want to hear from you.
            </p>
          </div>

          {/* Brand Partners */}
          <section className="mb-16">
            <h2 className="font-headline font-bold text-xl text-text-primary mb-4">
              Brand partners
            </h2>
            <div className="space-y-4 text-[15px] text-text-secondary leading-[1.75]">
              <p>
                The SuppVis shop only includes products that meet our quality
                criteria: clinical dosing, bioavailable forms, third-party
                testing, no proprietary blends, and credible manufacturing
                standards. We curate this list independently of any commercial
                relationship.
              </p>

              <div>
                <p className="text-text-primary font-semibold mb-2">
                  What partnership can include:
                </p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>
                    Featured placement in non-personalized surfaces of the
                    SuppVis shop and browse pages, clearly disclosed as sponsored
                    or partnered
                  </li>
                  <li>
                    Inclusion in our broader product catalog where your products
                    meet our quality criteria
                  </li>
                  <li>
                    Co-marketing opportunities as the platform grows
                  </li>
                  <li>
                    Direct affiliate relationships outside of Amazon
                  </li>
                </ul>
              </div>

              <div>
                <p className="text-text-primary font-semibold mb-2">
                  What partnership cannot include:
                </p>
                <p>
                  Influence over personalized recommendations. When SuppVis
                  recommends a supplement to a specific user based on their
                  biology, conditions, medications, and goals, that
                  recommendation is generated by our engine from the underlying
                  evidence. No brand can pay to be recommended to a specific
                  user, and we will not negotiate this point.
                </p>
                <p className="mt-4 text-text-primary font-semibold italic">
                  We hold this line because it is the foundation of user trust,
                  which is the foundation of everything else we are building.
                </p>
              </div>
            </div>
          </section>

          {/* Research Partners */}
          <section className="mb-16">
            <h2 className="font-headline font-bold text-xl text-text-primary mb-4">
              Research partners
            </h2>
            <div className="space-y-4 text-[15px] text-text-secondary leading-[1.75]">
              <p>
                SuppVis is built on a deep base of peer-reviewed research,
                clinical guidelines, and condition-specific evidence. We are open
                to working with research institutions, universities, and clinical
                organizations who share our commitment to evidence-based
                supplementation.
              </p>
              <div>
                <p className="text-text-primary font-semibold mb-2">
                  What partnership might look like:
                </p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>
                    Surfacing your published research within our platform, with
                    full attribution
                  </li>
                  <li>
                    Collaboration on white papers or population-level findings
                    drawn from our anonymized datasets
                  </li>
                  <li>
                    Advisory relationships with researchers in nutrition,
                    pharmacology, and personalized medicine
                  </li>
                  <li>
                    Joint work on improving the quality and rigor of supplement
                    research itself
                  </li>
                </ul>
              </div>
              <p>
                If you are conducting research in supplements, longevity, or
                personalized nutrition and are looking for a platform that takes
                your work seriously, reach out.
              </p>
            </div>
          </section>

          {/* Distribution Partners */}
          <section className="mb-16">
            <h2 className="font-headline font-bold text-xl text-text-primary mb-4">
              Distribution and integration partners
            </h2>
            <div className="space-y-4 text-[15px] text-text-secondary leading-[1.75]">
              <p>
                We are exploring white-label and API integration opportunities
                with healthcare providers, wellness platforms, and corporate
                wellness programs who want to offer personalized supplement
                intelligence to their members.
              </p>
              <p>
                If you have an audience that would benefit from what SuppVis does
                — clinicians, wellness coaches, employer health programs,
                integrative health platforms — we should talk about what an
                integration could look like.
              </p>
            </div>
          </section>

          {/* Get in Touch */}
          <section>
            <h2 className="font-headline font-bold text-xl text-text-primary mb-3">
              Get in touch
            </h2>
            <p className="text-[15px] text-text-secondary leading-[1.75] mb-8">
              Tell us about your brand, your work, and what kind of partnership
              you have in mind. We read every message and reply to serious
              inquiries within five business days.
            </p>

            <PartnerForm />

            <p className="text-sm text-text-muted text-center mt-6">
              Or email us directly at{" "}
              <a
                href="mailto:partner@suppvis.health"
                className="text-accent hover:text-accent-hover transition-colors"
              >
                partner@suppvis.health
              </a>
            </p>
          </section>
        </div>
      </main>
      <Footer />
    </>
  );
}
